### PR TITLE
Update biorxivs

### PR DESCRIPTION
**Pull request by andreacosolo**
BioRxiv stores different versions of a manuscript. We should make sure that we have the most recent one in the database, especially regarding title and list of authors, since these metadata are used by another check in foursight to search in Pubmed when the manuscript is published.

### CODE REVIEW

**Comment by andreacosolo** [comment]
The last commit introduces a comparison between the current version in biorxiv and in the 4DN database, and only triggers an update when a difference is found. This is to prevent indexing items when not necessary (including Experiments and ExpSets linked to the Publication, which in turn are detected by other foursight checks as recently modified - e.g. higlass checks, hic table update check, ...). However, doing so introduces a little code duplication from the Publication _update() in fourfront.
We can discuss what is best and revert this commit in case.

**Comment by aschroed** [comment]
Have you explored the possibility of adding a biorxiv_version property to Publication schema and querying with biorxiv api to compare?  Seems a potentially more rigorous way to catch revisions though if the info we display hasn't really changed and the link to biorxiv still works and points to the latest probably not necessary to do the re-index/update?

Otherwise this seems a reasonable way to look for updates and not sure there is a good way to avoid the code duplication.

**Review by aschroed — APPROVED** [review]
See my comment but otherwise looks good.

**Comment by andreacosolo** [comment]
Wait to merge until addition of `version` in Publication schema is in production https://github.com/4dn-dcic/fourfront/pull/1602

**Pull request merged**
